project = 'REHex'
description = "Reverse Engineers' Hex Editor"
full_description = "\
Documentation for the API available to Lua plugins. You should probably start with the \
[rehex](modules/rehex.html) module. \
\
**NOTE**: This API is very new and lacking in features. If you can't find a way to do what you \
want with it, please open an issue on the [GitHub page](https://www.github.com/solemnwarning/rehex/). \
"
format = 'markdown'
sort = true
